<b>Author/User:</b> <b style="color:#6666ff">Sai Kumar Ramagiri</b><br>
<b>Author/User:</b> <b style="color:#e69900">27/07/2023</b><br>

<u><h1 style="color:#006699; text-align:center">PYTHON BASICS</h1></u>

<u><h2 style="color:#24478f; text-align:center">PROGRAMMING ASSIGNMENT 8</h2></u>


<h4 style=" color: #ff3300">Q1. Write a Python Program to Add Two Matrices?</h4>

<b style ="color: #00b386">Answer:</b> 

In [1]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print('Matrix a = ')
print(a)

print('\nMatrix b = ')
print(b)

Matrix a = 
[[1 2]
 [3 4]]

Matrix b = 
[[5 6]
 [7 8]]



<h4 style=" color: #ff3300">Q2. Write a Python Program to Multiply Two Matrices?</h4>

<b style ="color: #00b386">Answer:</b>

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

if a.shape[1] == b.shape[0]:
    
    c = np.ones((a.shape[1],b.shape[0]), dtype='int')
    
    for i in range(0,len(a)):
        
        for j in range(0,len(b[0])):
            
            for k in range(0,len((b))):
                
                c[i][j] += a[i][j]*b[k][j]
    
    print(c)
else:
    
    print("Matrix multiplication rules are not matching.")



[[13 29]
 [37 57]]



<h4 style=" color: #ff3300">Q3. Write a Python Program to Transpose a Matrix?/h4>

<b style ="color: #00b386">Answer:</b>

In [3]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
a.T

r = np.ones((a.shape[1],a.shape[0]), dtype='int')

for i in range(0,r.shape[0]):
    
    for j in range(0, a.shape[0]):
        
        r[i][j] = a[j][i]

r

[[1 2]
 [3 4]
 [5 6]]


array([[1, 3, 5],
       [2, 4, 6]])


<h4 style=" color: #ff3300">Q4. Write a Python Program to Sort Words in Alphabetic Order?</h4>

<b style ="color: #00b386">Answer:</b>


In [4]:
l = ['this','is','totally','unclear','assignment']
sorted(l)

['assignment', 'is', 'this', 'totally', 'unclear']


<h4 style=" color: #ff3300">Q5. Write a Python Program to Remove Punctuation From a String?</h4>

<b style ="color: #00b386">Answer:</b>

In [5]:
s = 'THis is , & awesome! '
s = s.replace("&",'')
s = s.replace(",",'')
s = s.replace("!",'')
s

'THis is   awesome '