<b>Author/User:</b> <b style="color:#6666ff">Sai Kumar Ramagiri</b><br>
<b>Author/User:</b> <b style="color:#e69900">01/08/2023</b><br>

<u><h1 style="color:#006699; text-align:center">PYTHON BASICS</h1></u>

<u><h2 style="color:#24478f; text-align:center">PROGRAMMING ASSIGNMENT 13</h2></u>


<h4 style=" color: #ff3300">Q1: Write a program that calculates and prints the value according to the given formula:<br>
Q = Square root of [(2 * C * D)/H]<br>

Following are the fixed values of C and H:<br>
C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated sequence.

Example:
Let us assume the following comma separated input sequence is given to the program:
100,150,180
The output of the program should be:
18,22,24</h4>

<b style ="color: #00b386">Answer:</b> 

In [1]:
import math
#Q = math.sqrt((2 * C * D)/H)

C = 50
H = 30

s = str.split(input('Enter one or multiple values of D seperated by comma(,): '),",")

r =[]

for i in s:
    
    D = int(i)
    Q = math.sqrt((2 * C * D)/H)
    r.append(str(int(Q)))

print(",".join(r))

Enter one or multiple values of D seperated by comma(,): 100,150,180
18,22,24



<h4 style=" color: #ff3300">Q2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
    
Note: i=0,1.., X-1; j=0,1,¡Y-1.

Example:
Suppose the following inputs are given to the program:

3,5
Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]</h4>

<b style ="color: #00b386">Answer:</b>

In [2]:
import numpy as np

X = int(input('Enter the number of number of rows for 2-Dimensional array: '))
Y = int(input('Enter the number of number of rows for 2-Dimensional array: '))

two_d_array = np.ones((X,Y),dtype=int)

for i in range(0,X):
    for j in range(0,Y):
        
        two_d_array[i][j] = i*j

print(two_d_array)

Enter the number of number of rows for 2-Dimensional array: 3
Enter the number of number of rows for 2-Dimensional array: 5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]



<h4 style=" color: #ff3300">Q3: Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.
    
<br>Suppose the following input is supplied to the program:<BR>
without,hello,bag,world

Then, the output should be:
<br>bag,hello,without,world</h4>

<b style ="color: #00b386">Answer:</b>

In [3]:
s = str.split(input('Enter one or multiple values of D seperated by comma(,): '),",")
s.sort()
",".join(s)

Enter one or multiple values of D seperated by comma(,): without,hello,bag,world


'bag,hello,without,world'


<h4 style=" color: #ff3300">Q4: Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

<br>Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world</h4>

<b style ="color: #00b386">Answer:</b>


In [4]:
s = str.split(input('Enter one or multiple values of D seperated by space(" "): ')," ")
" ".join(list(set(s)))

Enter one or multiple values of D seperated by space(" "): hello world and practice makes perfect and hello world again


'again and world hello makes perfect practice'


<h4 style=" color: #ff3300">Q5: Write a program that accepts a sentence and calculate the number of letters and digits.
    
<br>Suppose the following input is supplied to the program:
hello world! 123
<br>Then, the output should be:
LETTERS 10</h4>

<b style ="color: #00b386">Answer:</b>

In [5]:
s = input('Enter any setence: ')

letters = 0
digits = 0
for i in s:
    if str.isalpha(i):
        letters += 1
    if str.isdigit(i):
        digits += 1

print('LETTERS: ',letters)
print('DIGITS: ',digits)

Enter any setence: hello world! 123
LETTERS:  10
DIGITS:  3



<h4 style=" color: #ff3300">Q6: A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

Following are the criteria for checking the password:
- 1. At least 1 letter between [a-z]
- 2. At least 1 number between [0-9]
- 1. At least 1 letter between [A-Z]
- 3. At least 1 character from [$#@]
- 4. Minimum length of transaction password: 6
- 5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, eachseparated by a comma.

Example:

<br>If the following passwords are given as input to the program:
ABd1234@1,a F1#,2w3E*,2We3345
<br>Then, the output of the program should be:
ABd1234@1</h4>

<b style ="color: #00b386">Answer:</b>

In [6]:
import string

s = str.split(input('Enter one or multiple values of passwords seperated by comma(","): '),",")

r = []
for i in s:
    if(len(i)>= 6 and len(i)<= 12):

        c = True
        c1 = c2 = c3 = c4 = False
        for j in i:
            
            if j in string.ascii_lowercase:
                c1 = True
                continue
            elif j in string.ascii_uppercase:
                c2 = True
                continue
            elif j in '$#@':
                c3 = True
                continue
            elif j in string.digits:
                c4 = True
                continue
            else:
                c =False
                break
            

                
        if c:
            
            if (c1==True) and (c2==True) and (c3==True) and (c4==True):

                r.append(i)

print(",".join(r))

Enter one or multiple values of passwords seperated by comma(","): ABd1234@1,a F1#,2w3E*,2We3345
ABd1234@1
