<b>Author/User:</b> <b style="color:#6666ff">Sai Kumar Ramagiri</b><br>
<b>Author/User:</b> <b style="color:#e69900">27/07/2023</b><br>

<u><h1 style="color:#006699; text-align:center">PYTHON BASICS</h1></u>

<u><h2 style="color:#24478f; text-align:center">PROGRAMMING ASSIGNMENT 7</h2></u>


<h4 style=" color: #ff3300">Q1. Write a Python Program to find sum of array?</h4>

<b style ="color: #00b386">Answer:</b> 

In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
a.sum()

15


<h4 style=" color: #ff3300">Q2. Write a Python Program to find largest element in an array?</h4>

<b style ="color: #00b386">Answer:</b>

In [2]:
a = np.array([1,2,3,4,5])
a.max()

5


<h4 style=" color: #ff3300">Q3. Write a Python Program for array rotation?</h4>

<b style ="color: #00b386">Answer:</b>

In [3]:
a = np.array([1,2,3,4,5])
a[::-1]

array([5, 4, 3, 2, 1])


<h4 style=" color: #ff3300">Q4. Write a Python Program to Split the array and add the first part to the end?</h4>

<b style ="color: #00b386">Answer:</b>


In [4]:
a = np.array([1,2,3,4,5])
print(a[0:3])
print('array : ',a)
np.append(a,a[0:3])

[1 2 3]
array :  [1 2 3 4 5]


array([1, 2, 3, 4, 5, 1, 2, 3])


<h4 style=" color: #ff3300">Q5. Write a Python Program to check if given array is Monotonic?</h4>

<b style ="color: #00b386">Answer:</b>

In [5]:
a = np.array([1,2,3,4,5])

print('Array: ',a)

v = True
for i in range(0,len(a)):

    if(all(a[i] > a[i+1:]) | all(a[i] < a[i+1:])):
        continue
    else:
        print('Not monotic')
        v = False
        break

if v:
    print('Array is monotonic')

Array:  [1 2 3 4 5]
Array is monotonic
